### ISSUE TITLE
Add jetty:run as an option to test with

### ISSUE THREAD

**Issue by bakersemail** [leleuj/cas-openid-demo#1]
Hi, this looks very useful.

But it would be great if it were simpler to try out.
Perhaps making the server and client able to start with: mvn jetty:run would be helpful to try this out quickly.

Some more instructions on how to use this would also be helpful.

**Comment by leleuj** [comment]
I like the idea. Though, I'm not sure it will be easy to do as I have two webapps to start : I'll see what I can do...

Any clue or pull request would be appreciated.

**Comment by leleuj** [comment]
I found a solution to use jetty:run. I update and improve the presentation of this project.

Can you send me a feedback on this ? so I can close this issue...

Thx
