### ISSUE TITLE
org.jasig.cas:cas-server-core-authentication 301 Moved Permanently

### ISSUE THREAD

**Issue by WernerRaath** [leleuj/cas-openid-demo#3]
Hi Leleuj

Wanted to test your application out but when I run `mvn package` after cleaning, it throws the following error:
`Project ID: org.jasig.cas:cas-server-core-authentication
Reason: Error getting POM for 'org.jasig.cas:cas-server-core-authentication' from the repository: Unable to read local copy of metadata: Cannot read metadata from '/root/.m2/repository/org/jasig/cas/cas-server-core-authentication/4.3.0-SNAPSHOT/maven-metadata-jasig-legacy.xml': end tag name </body> must match start tag name <hr> from line 5 (position: TEXT seen ...</center>\r\n</body>... @6:8) 
  org.jasig.cas:cas-server-core-authentication:pom:4.3.0-SNAPSHOT
 for project org.jasig.cas:cas-server-core-authentication
`

This is of because the `maven-metadata-jasig-legacy.xml` file contains HTML explaining that the repo has moved permanently.

**Comment by leleuj** [comment]
It seems to properly build using the `4.2.0-RC2` release.
